name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FIREBASE_CLI_EXPERIMENTS: webframeworks
  NODE_ENV: production
  NODE_VERSION: '18.20.7'
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive
        env:
          FIREBASE_TOKEN: 1//0674amXrhuiPGCgYIARAAGAYSNwF-L9IrowmcqxCCTj6lTgSgCiI4PDJFupkASlOzMB7LV8LwYZztjG_E2ul48soCYlbWSmihVT0
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Cleanup service account key
        if: always()
        run: rm -f ${{ github.workspace }}/service-account.json

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: build-logs
          path: |
            .next/
            firebase-debug.log
            .firebase/
          retention-days: 5
